### ISSUE TITLE
Automatizar el proceso (... y preguntas)

### ISSUE THREAD

**Issue by humitos** [cacrespo/tutorial_python_ES#2]
Acabo de seguir el README al pie de la letra y logré terminar con el PDF funcionando, pero...

- las instrucciones usan números de líneas como referencia, lo cual es muy probable que cambie en un futuro --al día de hoy no sé si estoy modificando las líneas correctas o no
- muchas de las instrucciones del README pueden estar directamente en el archivo `conf.py` utilizando la configuración de Sphinx (https://www.sphinx-doc.org/en/master/latex.html) 
- falta el paso final que es ingresar al directorio `./tutorial_latex` y ejecutar `make all-pdf`
- tuve que instalar algunas dependencias en el sistema
- estos dos no los encontré en `sphinx.sty`: `\newif\ifsphinxverbatimwithminipage \sphinxverbatimwithminipagetrue` y `\fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}}`
- todavía no sé cómo eliminar automaticamente las notas de pie que no tienen contenido (`\subsubsection*{Notas al pie}`)
- usando el `cover-front.pdf`, muestra una fecha antigua: ¿cuál es el original para re-generar ese documento? (lo mismo para el back)

Hice varios avances en esto. Acá dejo el diff con respecto al `conf.py` que tenemos en el otro repositorio. Voy a seguir trabajando en esto para dejarlo mejor de lo que lo tengo ahora, pero lo voy subiendo acá para ir compartiendo el trabajo de momento.

```python
# conf.py

# Define the document to build with LaTeX
latex_documents = [
    ('tutorial/index', 'Tutorial-Python_Python-Argentina.tex', u'Tutorial de Python',
     _stdauthor, 'manual'),
]

# Configure PDF building for PRINTED version of the Tutorial
# https://www.sphinx-doc.org/en/master/latex.html
#
# Install `latex-mk` and `texlive-latexextra` and `texlive-fontsextra`
# on the system using its own package manager
latex_elements = {
    'papersize': 'a5paper',
    'sphinxsetup': 'verbatimwithframe=false',
    'fontpkg': r'''
\setmainfont{FreeSerif}[
  Extension      = .otf,
  UprightFont    = *,
  ItalicFont     = *Italic,
  BoldFont       = *Bold,
  BoldItalicFont = *BoldItalic,
  Scale          = 0.9
]
\setsansfont{FreeSans}[
  Extension      = .otf,
  UprightFont    = *,
  ItalicFont     = *Oblique,
  BoldFont       = *Bold,
  BoldItalicFont = *BoldOblique,
  Scale          = 0.9
]
\setmonofont{FreeMono}[
  Extension      = .otf,
  UprightFont    = *,
  ItalicFont     = *Oblique,
  BoldFont       = *Bold,
  BoldItalicFont = *BoldOblique,
  Scale          = 0.9
]
''',
    'geometry': r'''\usepackage{geometry}\geometry{ right=20mm, left=10mm }''',
    'hyperref': r'''\usepackage[hidelinks]{hyperref}''',
    'maketitle': r'''
\includepdf[pages=-]{../../tutorial_python_ES/portada/cover-front.pdf}
''',
    'preamble': r'''
\usepackage{pdfpages}
''',
    'passoptionstopackages': r'\PassOptionsToPackage{gray}{xcolor}',
    'fvset': r'''\fvset{fontsize=\footnotesize}''',
    'printindex': r'''
\renewcommand{\indexname}{Índice}
\printindex
\includepdf[pages=-]{../../tutorial_python_ES/portada/cover-back.pdf}
''',
}
latex_show_urls = 'inline'
```

----

Entonces, usando esta modificación, solo se necesita:

1. instalar todas las dependencias del sistema
1. clonar el repositorio de la traducción
1. ejecutar `make build`
1. modificar el `conf.py` con este contenido (se podría automatizar también)
1. ejecutar `./venv/bin/sphinx-build -j auto -W --keep-going -b latex -d cpython/Doc/build/doctree/tutorial -D language=es . tutorial_latex`
1. ingresar al directorio `tutorial_latex`
1. ejecutar `make all-pdf`

[¡Ya tenemos el PDF en `Tutorial-Python_Python-Argentina.pdf`!](https://github.com/cacrespo/tutorial_python_ES/files/9894380/Tutorial-Python_PythonArgentina.pdf)

Coordinemos cómo seguimos 😍

**Comment by humitos** [comment]
Acá hay un documento con algunas de las páginas especiales para usar de referencia, https://docs.google.com/presentation/d/1K5YLEaoNkYl1gVo5bxvBmTHED5pfFl7ZI-_W_OQGNdw/edit#slide=id.g15c85e505c8_0_5

**Comment by humitos** [comment]
Utilicé ese documento para crear 3 archivos:

- `initial-pages.pdf`: contiene la tapa y las primeras páginas. Se inserta en el PDF **antes que cualquier otra cosa**
- `before-index.pdf`: contiene el logo de la Ñ hecha con todos los nombres de los traductores. Se inserta al final, pero antes del índice alfabético
- `cover-back.pdf`: contiene la contraportada. Se inserta **al final del archivo** 

Si se necesitan más páginas especial, me lo hacen saber. cc @facundobatista @cacrespo 

[Acá dejo un ejemplo utilizando esas páginas: Tutorial-Python_Python-Argentina.pdf](https://github.com/cacrespo/tutorial_python_ES/files/9895375/Tutorial-Python_Python-Argentina.pdf)

**Comment by cacrespo** [comment]
:wave: Hola @humitos! Qué alegría leerte por aquí. 

> - las instrucciones usan números de líneas como referencia, lo cual es muy probable que cambie en un futuro --al día de hoy no sé si estoy modificando las líneas correctas o no
> - muchas de las instrucciones del README pueden estar directamente en el archivo conf.py utilizando la configuración de Sphinx (https://www.sphinx-doc.org/en/master/latex.html)
> - falta el paso final que es ingresar al directorio ./tutorial_latex y ejecutar make all-pdf

Sí... se quedan super cortas las instrucciones. Básicamente lo que me pasó fue que una vez que tuve una primer salida más o menos aceptable continué trabajando el documento con un editor latex.

Respecto a la salida de ejemplo, aún tiene algunos inconvientes:
- el margen no se respeta en los agregados
- los capítulos empiezan por la hoja izquierda (quedó al revés)
- el índice del final quedó mal (además de que en esta primer versión lo excluimos).

Voy a integrar y documentar tus ajustes y (tratar de) resolver los pendientes de la misma manera que lo hiciste trabajando sobre el archivo `.conf`.

En este [hilo](https://pyar.discourse.group/t/imprimiendo-el-tutorial-de-python-en-castellano/803/9) hay un intercambio que tuvimos con Facu respecto a algunos de estos ajustes que menciono más arriba.

Actualmente la persona que nos va a ayudar con la portada y la impresión tiene [estos archivos](https://docs.google.com/presentation/d/1K5YLEaoNkYl1gVo5bxvBmTHED5pfFl7ZI-_W_OQGNdw/edit?usp=share_link):
- pdf con el contenido desde el índice hasta capitulo 13
- draft de tapa y contrapa
Y va a embellecerlo y juntar todo. En cuánto nos retorne el archivo lo cuelgo por aquí así podemos reproducirlo y/o tomarlo como modelo.

Muchas gracias!!! :smile::smile::smile:

**Comment by humitos** [comment]
> Básicamente lo que me pasó fue que una vez que tuve una primer salida más o menos aceptable continué trabajando el documento con un editor latex.

Mi recomendación es tratar de hacer todas las modificaciones desde Sphinx, ya que una vez que empezás a tocar los otros archivos a mano, ya no puedes volver a generarlos con una versión más actualizada de la traducción.

> Respecto a la salida de ejemplo, aún tiene algunos inconvientes:

Sí, algunas cosas no las encontré en los archivos .sty como mencioné; pero hablando un poco con vos y leyendo el hilo que tienen con Facu, en 15 minutos lo arreglamos 😉 

> Voy a integrar y documentar tus ajustes y (tratar de) resolver los pendientes de la misma manera que lo hiciste trabajando sobre el archivo `.conf`.

Tengo una rama más avanzada. Si querés coordinamos el trabajo para no pisarnos.

> En cuánto nos retorne el archivo lo cuelgo por aquí así podemos reproducirlo y/o tomarlo como modelo.

Perfecto.

**Comment by humitos** [comment]
Estuve trabajando un poco más en esto. No está completo aún. Abrí #4 para seguir esa lista de TODOs.

Sería bueno si puedes probar lo que hice en mi fork: https://github.com/humitos/tutorial-python-impreso y ver si lográs obtener el PDF. Sobre eso podemos seguir trabajando juntos luego, creo yo.

**Comment by humitos** [comment]
En https://github.com/humitos/tutorial-python-impreso/ tengo el proceso ya automatizado. Faltaría que te funcione a vos de la misma forma que me funciona a mi 🙃
