### ISSUE TITLE
Archivos "extra" en el repositorio

### ISSUE THREAD

**Issue by humitos** [cacrespo/tutorial_python_ES#3]
Luego de haber hecho #2, veo que hay muchos archivos en el repositorio que no son necesarios ya que Sphinx los genera al momento de ejecutar `sphinx-build`. ¿Cuál es el objetivo de esos archivos? ¿Se pueden eliminar?

**Comment by cacrespo** [comment]
En su momento había hecho un "barrido" de cada uno de estos archivos para limpiar los que eran inútiles en el marco de imprimir exclusivamente el tutorial manteniendo el estilo visual y demás. 

Se supone :eyes: que los que quedaron son absolutamente necesarios. Obviamente borremos todo lo que esté demás.

**Comment by humitos** [comment]
Parece que ya hiciste merge de algunos de mis commits que borran estos archivos. Siempre los podemos recuperar de la historia si los necesitamos 👍🏼
